version: "3.9"
services:
  flask:
    build: .
    command: flask run --host 0.0.0.0
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./:/root
